### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by antoalli** [rohithpeddi/SceneSayer#14]
Hi everyone,
Thank you so much for the fantastic work and for making the code open source! I’m currently trying to reproduce the results from the paper, but I’m a bit confused about the correct testing flow.
I’ve noticed that there are two types of functions being called:
-"process_test_video_future_frame" and "compute_test_video_future_frame_score"
-"process_test_video_context" and "compute_test_video_context_score"
The second option is currently commented out in the test class from which the specific methods inherit. Could you clarify the purpose of each approach and which one is used to reproduce the results from the paper?
Additionally, I’m unsure how non-continuous objects are handled. Are these removed from the ground truth when calculating the paper’s results?

Thank you very much,
Antonio

**Comment by rohithpeddi** [comment]
@antoalli Thank you for your interest in our work. 

We used two types of evaluations to check the model's performance. 

1. Anticipating relationships in the next few frames. (Appendix G)
2. Anticipating relationships for the whole video.  (Appendix H)

In the main paper, we reported results corresponding to option 2 (Appendix H).

We handled the non-continuous objects during training by following the strategy.
Given a context window, as future object prediction is a hard problem, we assume the presence of a weaker model that always predicts that the same objects observed in the last context frame shall be observed in the future.

Simply put, we devised a masking strategy for future frames. Check [here](https://github.com/rohithpeddi/SceneSayer/blob/3014b71b76b279b84d245efe987c45cc96f33a21/lib/supervised/sga/base_transformer.py#L194) for transformer based models and [here](https://github.com/rohithpeddi/SceneSayer/blob/3014b71b76b279b84d245efe987c45cc96f33a21/lib/supervised/sga/scene_sayer_sde.py#L259) for differential equation-based models. 

During the evaluation, we use the future relationship predictions for only objects observed in the last context frame and compare them with the actual ground truth (thus, the reason for the lower numbers even in the Grounded Action Genome Scenes settings (Predicate Classification in SGG literature).)

**Comment by antoalli** [comment]
I see. So, numbers in main paper tables report anticipation results for all frames that are subsequent to the specified context portion (as in appendix H), regardless of the anticipation horizon that has been during training. 

Regarding the non-continuous objects, my understanding is that you're masking from the GT scene graphs (all future graphs untill the end of video) all relationships involving objects that were not present in the last context frame seen by the model, right? 
If I am correct can you point me where this is performed for differential equation-based models? 
I see the logic in the forward function you linked in previous message, but it isn’t actually used during testing. Instead, the forward_single_entry function is used.

p.s. thanks a lot :)

**Comment by rohithpeddi** [comment]
Yes, @antoalli, you are correct. We perform masking as described, but only during training to estimate loss. 
To be more precise, we do the following things during training and testing:

**Training:** 

1. Context Window starting with 3 frames to N-1 frames (where N is the total number of frames for a video).
2. For each size of the context window, 
     - We consider objects present in the last context frame 
     - Construct the relationship representations between these objects
     - Estimate their relationship representations, assuming that the objects persist in the video in future frames.
     - Take the intersection of the objects present in the last context frame and the subsequent future frames
     - Estimate relationship level loss for the common objects. 

**Testing**

1. Context Fraction Results:
  - Results corresponding to the ones mentioned in the paper
  - We take 4 contexts for each video in the test set.
  - Take the objects present in the last context frame
  - Assuming that objects persist, estimate the scene graphs for future frames (corresponding to the rest of the video)
  - Compare these estimated graphs with ground truth scene graphs.
 2. **We do not mask anything during testing.** 
 3. We directly use these predicted future scene graphs and compare them with ground truth scene graphs. 
 4. As conveyed and correctly noticed, forward_single_entry estimates these future scene graphs using trained models and compares them with ground truth scene graphs.
