### ISSUE TITLE
Faster RCNN pretrained model

### ISSUE THREAD

**Issue by Natsushiro** [rohithpeddi/SceneSayer#15]
Hello, thank you for your great work!
The link of the pretrained faster rcnn model seems to be deprecated. Would you mind to update the link, or may I know is that a pre-trained model released by other works?
Thanks a lot.

**Comment by rohithpeddi** [comment]
Hi, 
Thank you for your interest in our work. 
Can you try using this [LINK](https://utdallas.box.com/s/1pspm5x8etlczoklyw4bclotsmlejagj) to download the file. 

Regards, 
Rohith
